const mongoose = require('mongoose');

const orderSchema = new mongoose.Schema({
  userId:       { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  customerName: { type: String, required: true },
  phone:        { type: String, required: true },
  email:        { type: String, default: '' },
  address:      { type: String, required: true },
  landmark:     { type: String, default: '' },
  village:      { type: String, default: '' },
  district:     { type: String, default: '' },
  city:         { type: String, default: '' },
  state:        { type: String, default: 'Punjab' },
  pincode:      { type: String, required: true },
  items: [{
    productId:    { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
    name:         String,
    company:      String,
    dimensions:   String,
    pricePerSqFt: Number,
    squareFeet:   Number,
    totalPrice:   Number,
  }],
  subtotal:             { type: Number, required: true },
  transportationCharge: { type: Number, default: 0 },
  labourCharge:         { type: Number, default: 0 },
  discount:             { type: Number, default: 0 },
  couponApplied:        { type: String, default: '' },
  distanceKm:           { type: Number, default: 0 },
  distanceNote:         { type: String, default: '' },
  totalSqft:            { type: Number, default: 0 },
  totalWeightKg:        { type: Number, default: 0 },
  adminTransportOverride: { type: Number, default: null },
  adminLabourOverride:    { type: Number, default: null },
  adminNote:              { type: String, default: '' },
  driverPhone:            { type: String, default: '' },
  driverName:             { type: String, default: '' },
  vehicleNumber:          { type: String, default: '' },
  totalAmount:          { type: Number, required: true },
  status:        { type: String, enum: ['pending','confirmed','out_for_delivery','delivered'], default: 'pending' },
  paymentMethod: { type: String, default: 'COD' },
}, { timestamps: true });

module.exports = mongoose.model('Order', orderSchema);
